import "./globals.css";
// import { Inter } from "next/font/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <main className={`font-mono tracking-tighter min-h-screen bg-background flex flex-col bg-zinc-800 text-zinc-300`}>
                    {children}
                </main>
            </body>
        </html>
    );
}
